cpu                    = 4
cores-per-socket       = 1
ram                    = 4096
disksize               = 100 # in GB
vm-guest-id            = "ubuntu64Guest"
vsphere-unverified-ssl = "true"
vsphere-datacenter     = "NSX-T"
vsphere-cluster        = "prod"
vm-datastore           = "esxi1"
vm-network             = "DPortGroup"
dns_server_list        = ["8.8.8.8"]
name                   = "vm_vrf-"
vm-template-name       = "Ubuntu-2204-Template-100GB-Thin"
